Repository sports-club-hanzan/virtual-pilgrimage, pull requests merged in 2022-10, with the labels that each got.

#29 Firebase に関する実装・設定の初期設定
  firebase/.firebaserc
  firebase/.gitignore
  firebase/README.md
  firebase/firebase.json
  firebase/firestore.indexes.json
  firebase/firestore.rules
  firebase/package-lock.json
  firebase/package.json
  firebase/schema.yaml
  firebase/storage.rules
  firebase/tests/firestore.rules.test.ts
  firebase/tsconfig.json
Labels: Firebase

#42 お遍路の進捗を更新するロジックの実装
  lib/domain/auth/sign_in_interactor.dart
  lib/domain/pilgrimage/update_pilgrimage_progress_interactor.dart
  lib/domain/pilgrimage/update_pilgrimage_progress_result.dart
  lib/domain/pilgrimage/update_pilgrimage_progress_usecase.dart
  lib/domain/temple/temple_info.codegen.dart
  lib/domain/temple/temple_info.codegen.freezed.dart
  lib/domain/temple/temple_info.codegen.g.dart
  lib/domain/temple/temple_repository.dart
  lib/domain/user/health/health_info.codegen.dart
  lib/domain/user/health/health_info.codegen.freezed.dart
  lib/domain/user/health/health_info.codegen.g.dart
  lib/domain/user/health/health_repository.dart
  lib/domain/user/health/update_health_interactor.dart
  lib/domain/user/health/update_health_result.dart
  lib/domain/user/pilgrimage/pilgrimage_info.codegen.dart
  lib/domain/user/pilgrimage/pilgrimage_info.codegen.freezed.dart
  lib/domain/user/pilgrimage/pilgrimage_info.codegen.g.dart
  lib/domain/user/virtual_pilgrimage_user.codegen.dart
  lib/domain/user/virtual_pilgrimage_user.codegen.freezed.dart
  lib/domain/user/virtual_pilgrimage_user.codegen.g.dart
  lib/infrastructure/temple/temple_repository_impl.dart
  lib/infrastructure/user/health_repository_impl.dart
  lib/ui/pages/home/components/google_map_view.dart
  lib/ui/pages/home/home_page.dart
  lib/ui/pages/home/home_presenter.dart
  lib/ui/pages/profile/profile_page.dart
  lib/ui/pages/profile/profile_presenter.dart
  lib/ui/pages/sign_in/sign_in_presenter.dart
  test/analytics_test.dart
  test/domain/auth/sign_in_interactor_test.dart
  test/domain/pilgrimage/update_pilgrimage_progress_interactor_test.dart
  test/domain/user/health/update_health_interactor_test.dart
  test/domain/user/profile/update_user_profile_image_interactor_test.dart
  test/domain/user/registration/user_registration_interactor_test.dart
  test/helper/mock_query_document_snapshot.dart
  test/infrastructure/temple/temple_repository_impl_test.dart
  test/infrastructure/user/health_repository_impl_test.dart
  test/infrastructure/user/user_repository_impl_test.dart
  test/ui/components/bottom_navigation_test.dart
  test/ui/pages/profile/profile_presenter_test.dart
Labels: 機能開発

#46 サインイン・ユーザ登録ページの改善
  lib/domain/auth/sign_in_interactor.dart
  lib/domain/auth/sign_in_usecase.dart
  lib/domain/exception/sign_in_exception.dart
  lib/domain/user/pilgrimage/pilgrimage_info.codegen.dart
  lib/domain/user/pilgrimage/pilgrimage_info.codegen.freezed.dart
  lib/domain/user/registration/user_registration_interactor.dart
  lib/model/form_model.codegen.dart
  lib/model/radio_button_model.codegen.dart
  lib/model/radio_button_model.codegen.freezed.dart
  lib/ui/components/atoms/primary_button.dart
  lib/ui/components/atoms/secondary_button.dart
  lib/ui/components/gender_radio_buttons.dart
  lib/ui/components/my_text_form_field.dart
  lib/ui/pages/profile/components/profile_health_card.dart
  lib/ui/pages/profile/profile_page.dart
  lib/ui/pages/registration/registration_page.dart
  lib/ui/pages/registration/registration_presenter.dart
  lib/ui/pages/registration/registration_state.codegen.dart
  lib/ui/pages/registration/registration_state.codegen.freezed.dart
  lib/ui/pages/sign_in/sign_in_page.dart
  lib/ui/pages/sign_in/sign_in_presenter.dart
  lib/ui/pages/sign_in/sign_in_state.codegen.dart
  lib/ui/pages/sign_in/sign_in_state.codegen.freezed.dart
  lib/ui/style/color.dart
  lib/ui/style/font.dart
  lib/ui/style/theme.dart
  test/domain/auth/sign_in_interactor_test.dart
  test/domain/user/health/update_health_interactor_test.dart
  test/domain/user/registration/user_registration_interactor_test.dart
  test/helper/default_mock_firebase_crashlytics.dart
Labels: 改善

#55 ホームページのUI改善
  lib/analytics.dart
  lib/domain/pilgrimage/update_pilgrimage_progress_interactor.dart
  lib/domain/user/registration/user_registration_interactor.dart
  lib/domain/user/registration/user_registration_usecase.dart
  lib/router.dart
  lib/ui/components/molecules/my_drawer.dart
  lib/ui/components/molecules/pilgrimage_progress_card.dart
  lib/ui/components/molecules/profile_health_card.dart
  lib/ui/components/my_app_bar.dart
  lib/ui/pages/home/components/google_map_view.dart
  lib/ui/pages/home/home_page.dart
  lib/ui/pages/home/home_presenter.dart
  lib/ui/pages/profile/profile_page.dart
  lib/ui/pages/profile/profile_presenter.dart
  lib/ui/pages/registration/registration_page.dart
  lib/ui/pages/registration/registration_presenter.dart
  lib/ui/pages/sign_in/sign_in_page.dart
  lib/ui/pages/sign_in/sign_in_presenter.dart
  test/domain/user/registration/user_registration_interactor_test.dart
Labels: 改善

#50 お寺一覧ページの追加
  firebase/schema.yaml
  firebase/temples/temple_info_update.csv
  lib/domain/temple/temple_info.codegen.dart
  lib/domain/temple/temple_info.codegen.freezed.dart
  lib/domain/temple/temple_info.codegen.g.dart
  lib/router.dart
  lib/ui/components/bottom_navigation.dart
  lib/ui/pages/temple/temple_detail_dialog.dart
  lib/ui/pages/temple/temple_page.dart
  test/ui/components/bottom_navigation_test.dart
Labels: feature
